# Generated by Django 3.2.5 on 2021-07-29 08:17

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='static/img/menprofile_mirh47.png', max_length=255, null=True, verbose_name='image')),
                ('occupation', models.CharField(blank=True, max_length=140, null=True)),
                ('facebook', models.CharField(blank=True, max_length=140, null=True)),
                ('twitter', models.CharField(blank=True, max_length=140, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=140, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

print("--hello--"*20)