# Generated by Django 3.2.5 on 2021-07-25 12:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/img/menprofile_mirh47.png', max_length=255, verbose_name='image'),
        ),
    ]
