# Generated by Django 3.2.5 on 2021-07-19 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cimbomwebblog', '0002_auto_20210719_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cimbomwebblog.category'),
        ),
    ]
