# Generated by Django 3.2.5 on 2021-07-19 11:32

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cimbomwebblog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to='media/'),
        ),
    ]
