# Generated by Django 3.2.5 on 2021-07-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimbomwebblog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(max_length=200),
        ),
    ]
