# Generated by Django 3.2.5 on 2021-07-22 13:23

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cimbomwebblog', '0006_alter_post_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default=None, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', sorl.thumbnail.fields.ImageField(default=None, upload_to='static/img')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('number', models.CharField(default=None, max_length=2, null=True, unique=True)),
                ('country', models.CharField(max_length=60)),
                ('salary', models.CharField(max_length=60)),
                ('foot', models.CharField(choices=[('RIGHT', 'Right'), ('LEFT', 'Left')], default=None, max_length=60)),
                ('height', models.CharField(max_length=60)),
                ('about', models.TextField(max_length=400)),
                ('pos', models.ManyToManyField(related_name='player_position', to='cimbomwebblog.Positions')),
            ],
        ),
    ]
