# Generated by Django 3.2.5 on 2021-07-22 14:23

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cimbomwebblog', '0007_players_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to=''),
        ),
    ]
