# Generated by Django 3.2.5 on 2021-07-25 05:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cimbomwebblog', '0007_players_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='photo',
        ),
        migrations.AddField(
            model_name='players',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
    ]
