# Generated by Django 3.2.5 on 2021-07-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cimbomwebblog', '0008_auto_20210725_0907'),
        ('cimbomwebblog', '0008_auto_20210725_0908'),
    ]

    operations = [
    ]
