# Generated by Django 3.2.5 on 2021-07-26 21:06

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cimbomwebblog', '0009_merge_0008_auto_20210725_0907_0008_auto_20210725_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
    ]
