# Generated by Django 3.2.5 on 2021-07-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cimbomwebblog', '0009_merge_0008_auto_20210725_0907_0008_auto_20210725_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='photo',
        ),
    ]
