# Generated by Django 3.2.5 on 2021-07-23 09:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cimbomwebblog', '0009_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='photo',
        ),
        migrations.AddField(
            model_name='players',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
