# Generated by Django 3.2.5 on 2021-07-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cimbomwebblog', '0002_auto_20210729_0311'),
        ('cimbomwebblog', '0010_remove_players_photo'),
    ]

    operations = [
    ]
